In [1]:
import pandas as pd

In [2]:
info = {
    "Name" : ["Suhail","Waseem","Naseem"],
    "CGPA" : [3.4,7.4,8.4]
}
df = pd.DataFrame(info)
print(df)

     Name  CGPA
0  Suhail   3.4
1  Waseem   7.4
2  Naseem   8.4

In [3]:
#Series in Pandas 1D Labeled Array 

s = pd.Series([1,2,3,4,5])
print(s)
print(type(s),"\n")

#Index in pandas
print(s[0])
print(s[2])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

1
3

In [4]:
a = pd.Series([24,25,26,27], index=["adam","eve","charlie","boob"])
print(a)

print(a["adam"])
print(a["boob"])

adam       24
eve        25
charlie    26
boob       27
dtype: int64
24
27

In [5]:
#Series Properties

#Vectorization is allowed in pandas becx we have homogenius data
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([10,20,30,40,50])

print(s1 + s2)

#Mutable Values in pandas
s1[0] = 100
print(s1)

#Immutable data in pandas
changed_s1 = s1.drop(0)
print(s1)
print(changed_s1)

0    11
1    22
2    33
3    44
4    55
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
#Data Frame of Dictonary
Info = {
    "Name" : ["Adam","Eye","Boob","Charlie"],
    "Age" : [24,25,26,27],
    "CGPA" : [8.5,7.4,9.3,7.2]
}
df = pd.DataFrame(Info)
print(df,type(df))

print(df.index)
print(df.columns)

      Name  Age  CGPA
0     Adam   24   8.5
1      Eye   25   7.4
2     Boob   26   9.3
3  Charlie   27   7.2 <class 'pandas.DataFrame'>
RangeIndex(start=0, stop=4, step=1)
Index(['Name', 'Age', 'CGPA'], dtype='str')

In [7]:
#Data_frame of list of list
df = pd.DataFrame([["Adam",24],["Eye",25],["Boob",29]], columns=["Name","Age"])
print(df)

   Name  Age
0  Adam   24
1   Eye   25
2  Boob   29

In [8]:
#Data_frame of numpy array 
import numpy as np
np_arr = np.array([[1,2,3],[4,5,6]])

df = pd.DataFrame(np_arr, columns=["A","B","C"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [9]:
#Import csv file from pandas
df = pd.read_csv("Employee_data.csv")
print(df,type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.DataFrame'>

In [10]:
#Import json file from pandas
df = pd.read_json("raw_data.json")
print(df,type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.DataFrame'>

In [11]:
#Data_frame method it is helpful for EDA


#df.head() #print starting 5 row
#df.tail(2) #print last 5 row
#df.sample(5) #print randow value
#df.info()   #print summery of data
#df.shape  #print (row,column)
#df.describe() #print all value with calculation
#df.columns  #print all columns data
#df.nunique() #print all uniqe data

In [12]:
#AQI With Data Set
df = pd.read_csv("globalAirQuality.csv")
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [13]:
#Selecting the data

#1=> select columns
df["city"]
df[["city","aqi"]]  

#2=> Select rows
df.loc[2]
df.loc[0:2]      #start index : end index (inclusive means include last index)

df.iloc[2]
df.iloc[0:3]     #start index : end index (exclusive means does not  include last index)

#3=> select cells- row and columns 

df.loc[0:2,["city","aqi"]]
df.columns
#df.index
#df.iloc[0:2,2]
df.loc[0:2,["country","city","latitude","longitude"]]
df.iloc[0:3,1:5]

#4=> select Single scaler value from at and iat

df.at[0,"city"]
df.iat[0,2]

#view not copy
cities = df["city"].copy()
cities[1] = "New York"
print(cities)

0        New York
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: str

In [14]:
#Selecting the data

#1=> select columns
df["city"]
df[["city","aqi"]]  

#2=> Select rows
df.loc[2]
df.loc[0:2]      #start index : end index (inclusive means include last index)

df.iloc[2]
df.iloc[0:3]     #start index : end index (exclusive means does not  include last index)

#3=> select cells- row and columns 

df.loc[0:2,["city","aqi"]]
df.columns
#df.index
#df.iloc[0:2,2]
df.loc[0:2,["country","city","latitude","longitude"]]
df.iloc[0:3,1:5]

#4=> select Single scaler value from at and iat

df.at[0,"city"]
df.iat[0,2]

#view not copy
cities = df["city"].copy()
cities[1] = "New York"
print(cities)

0        New York
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: str

In [15]:
#Filtering of data 

df [df["aqi"] > 100]  #filter data which is greater then 100 aqi 
df [ (df["aqi"] > 100) & (df["temperature"] > 30) ]
df [(df["aqi"] > 100) & (df["temperature"] < 30)]

aqi_data = df[(df["aqi"] > 100) & (df["temperature"] > 30)] [["city","aqi"]]
aqi_data.iloc[0]   #index start with zero
aqi_data.loc[6]    #in this data we put labled value 

#query method alwayes return copy not view
aqi_val = 100
df.query("aqi > 100 & temperature > 30")[["city","aqi"]]
df.query("aqi > @aqi_val & temperature > 30")[["city","aqi"]]

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

In [16]:
#Cleaning data 
df = pd.read_csv("raw_data.csv")

df.isnull()
df.isna()

df.isnull().sum()   #to find missing value in data 

df.dropna()   #drop all null value from row
df.dropna(axis=1) #drop all null value from row

df.fillna(100)    #fill all mising value from 0


#perticular any column value we can clean and set to a perticular value
age_mean = df["age"].mean()

cleaned_data = df.copy()
age_mean = cleaned_data["age"].mean()
cleaned_data["age"] = cleaned_data["age"].fillna(age_mean)


#forward fill
df.ffill()
#backword fill
df.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [17]:
#Handle Duplicate Data
df.duplicated()
df["country"].duplicated()
df[["country","gender"]].duplicated()

#remove duplicate value from data

#(inplace=True) when we replace original data from file
df.drop_duplicates()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [18]:
#Data Types

df.dtypes
df2 = df.copy()

df2 = df2.fillna(0)

df2["age"] = df2["age"].astype("int64").copy()
df2.dtypes

id           int64
name        object
age          int64
country     object
gender      object
income     float64
dtype: object

In [19]:
#Cleaning data handle string
df["gender"].str.lower()
df["gender"].str.upper()
df["gender"].str.capitalize()

#suhailazhr@gmail.com
#df["name"].str.split("@")  if we have split name from gmail

#if the value exist we can check throuh countains
df["country"].str.contains("india", case=False)

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8     False
9     False
10    False
Name: country, dtype: bool

In [20]:
#Transform of data (feature Engineering)
df2 = df.copy()

#def logic:
#    if (income < 50_000):



df2["tax"] = df2["income"].apply(lambda x : "20%" if x >= 50000 else "10%" )

gender_map = {"Male" : "M" , "Female" : "F" , "Unknown" : "U"}
df2["gender"] = df2["gender"].map(gender_map)

df2 = df2.assign(new_income = df["income"] * 1.1 )

#replace of any data from original data 
df2["country"] = df2["country"].replace("USA","United State")

#rename of the data 
df2.columns = ["ID","Name","Age","Country","Gender","Income","Tax","New_Income"]
df2.rename(columns={"Income":"Salary"})
df2.rename(index={1:"First"})

#Sort the data means assending order
df2.sort_values("Income")
df2 = df2.fillna(50)

#Sort the data means desending order
df2.sort_values("Income" , ascending=False)


#sort_data = ["Income","Age"]
sorted_df = df2.sort_values(["Income","Age"])

#Sort index value 
sorted_df.sort_index()

#reset index value 
sorted_df.reset_index()
sorted_df.reset_index(drop=True)  #we can drop the original index value from data 

#ranking method in pandas
#sorted_df["Ranking"] = sorted_df["Income"].rank( ascending=False, method="dense")
sorted_df[["ID","Name","Age","Country","Gender","Income","New_Income","Tax"]]

    ID          Name   Age       Country Gender   Income  New_Income  Tax
4    4  Maria Garcia  34.0         Spain      F     50.0        50.0  10%
9    9   Carlos Ruiz  50.0        Mexico      M  45000.0     49500.0  10%
3    3          Alex  50.0  United State      U  47000.0     51700.0  10%
5    5        Li Wei  27.0         China      M  51000.0     56100.0  20%
0    1      John Doe  29.0  United State      M  55000.0     60500.0  20%
1    1      John Doe  29.0  United State      M  55000.0     60500.0  20%
10  10   Emily Davis  31.0  United State     50  58000.0     63800.0  20%
8    8    Rachel Lee  29.0  United State      F  62000.0     68200.0  20%
2    2    Jane Smith  50.0        Canada      F  62000.0     68200.0  20%
7    7    Ahmed Khan  38.0            50      M  68000.0     74800.0  20%
6    6            50  45.0         India      F  73000.0     80300.0  20%

In [21]:
#Task ---> Shift id columns to the end

df2 = df.copy()

new_col_order = [col for col in df2.columns if col != "id"] + ["id"]

df2[new_col_order]

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
1       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10

In [37]:
#How to write a data in csv

df2 = df.copy()

df2 = df2.drop_duplicates()
df2 = df2.fillna(0)
df2 = df2.sort_values("income")
df2 = df2.reset_index(drop=True)
df2.to_csv("Sorted_data.csv")

In [38]:
df2

   id          name   age country   gender   income
0   4  Maria Garcia  34.0   Spain   Female      0.0
1   9   Carlos Ruiz   0.0  Mexico     Male  45000.0
2   3          Alex   0.0     USA  Unknown  47000.0
3   5        Li Wei  27.0   China     Male  51000.0
4   1      John Doe  29.0     USA     Male  55000.0
5  10   Emily Davis  31.0     USA        0  58000.0
6   2    Jane Smith   0.0  Canada   Female  62000.0
7   8    Rachel Lee  29.0     USA   Female  62000.0
8   7    Ahmed Khan  38.0       0     Male  68000.0
9   6             0  45.0   India   Female  73000.0